---

- hosts: PVC
  vars:
    msg: "This is server {{ ansible_hostname }}"

  tasks:
    - name: Install Python requests module
      apt:
          name: python3-requests
          state: present

    - community.docker.docker_network:
        name: devops-example
        ipam_config:
          - subnet: 10.0.0.0/24
            gateway: 10.0.0.1
            iprange: 10.0.0.0/26

    - community.docker.docker_container:
        name: app
        # Обязатлеьно указываем тег, который хотим деплоить
        # Если образа на сервере нет, Ansible его автоматически скачает
        image: "dsradozhitskiy/devops-example-app:{{ version }}"
        # Подключаем супервизор
        # Если контейнер остановится, например, из-за ошибок
        # супервизор докера его перезапустить
        restart_policy: always
        # Запускаем если не запущен
        state: started
        networks:
          - name: devops-example
        # Делаем доступным снаружи
        ports:
          - 3000:3000
        env: # Настраиваем
          NODE_ENV: production
          SERVER_MESSAGE: "{{ msg }}"

    - community.docker.docker_container:
        name: caddy
        image: "dsradozhitskiy/devops-example-caddy:{{ version }}"
        restart_policy: always
        state: started
        networks:
          - name: devops-example
        ports:
          - 80:80
          - 443:443
