name: Main CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: make compose-build

      - name: Install dependencies
        run: make compose-install

      - name: Run linter
        run: make compose-lint-ci

      - name: Run tests
        run: make compose-test-ci
