name: Main CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: make compose-build

      - name: Run linter
        run: make compose-lint-ci

      - name: Run tests
        run: make compose-test-ci

      - name: push
        run: make docker-push
